[package]
authors = ["shuuyu"]
description = "Updater task for Nabi"
edition = "2021"
license = "AGPL-3.0"
name = "insurge"
version = "1.0.0"

[target.'cfg(any(windows, unix, macos))']
rustflags = ["-C target-cpu=native"]

[features]
default = []

[dependencies]
log = "0.4.17"
toml = "0.5.9"
tokio = { version = "1.18.2", features = ["rt", "rt-multi-thread", 'macros'] }
futures = {version = "0.3.21"}

twilight-model = {version = "0.11.0"}
twilight-cache-inmemory = {version = "0.11.0"}
twilight-gateway = {version = "0.11.0"}
twilight-http = {version = "0.11.0"}
twilight-standby = {version = "0.11.0"}
twilight-embed-builder = {version = "0.11.0"}
twilight-mention = {version = "0.11.0"}
twilight-util = {version = "0.11.0"}
twilight-gateway-queue = {version = "0.11.0"}
